#ifndef NUMERIC_HPP
#define NUMERIC_HPP

#define RPL_WELCOME             001
#define RPL_NAMREPLY            353
#define RPL_ENDOFNAMES          366
#define RPL_NOTOPIC      331
#define RPL_TOPIC        332
#define RPL_INVITING     341
#define ERR_NOSUCHNICK          401
#define ERR_NOSUCHCHANNEL       403
#define ERR_CANNOTSENDTOCHAN    404
#define ERR_NONICKNAMEGIVEN     431
#define ERR_ERRONEUSNICKNAME    432
#define ERR_NICKNAMEINUSE       433
#define ERR_NOTONCHANNEL        442
#define ERR_NOTREGISTERED       451
#define ERR_NEEDMOREPARAMS      461
#define ERR_PASSWDMISMATCH      464
#define ERR_CHANNELISFULL       471
#define ERR_UNKNOWNMODE         472
#define ERR_INVITEONLYCHAN      473
#define ERR_BADCHANNELKEY       475
#define ERR_CHANOPRIVSNEEDED    482

#endif