server {
    listen 443 ssl;
    server_name imellali.42.fr;

    root /var/www/html;
    index index.php;

    ssl_certificate     /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location /static/ {
        proxy_pass http://static_site:8080/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ^~ /adminer/ {
        include fastcgi_params;
        fastcgi_pass adminer:9001;
        fastcgi_param SCRIPT_FILENAME /var/www/adminer/index.php;
        fastcgi_param SCRIPT_NAME /adminer/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/adminer;
        fastcgi_param HTTP_PROXY "";
    }

    location = /portainer {
        return 301 /portainer/;
    }
    location ^~ /portainer/ {
        proxy_pass http://portainer:9000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_pass wordpress:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\. {
        deny all;
    }
}
